USE [Academy]

CREATE TABLE [Groups]
(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL ,
[Name] NVARCHAR(10) NOT NULL CHECK (Len(Name)>1),
[Rating] INT NOT NULL CHECK(0<Rating and Rating<5),
[Year] INT NOT NULL CHECK(1<=Year and Year<=5)
)

CREATE TABLE [Departments]
(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL ,
[Financing] MONEY DEFAULT 0 NOT NULL CHECK(Financing>0),
[Name] NVARCHAR (100) NOT NULL CHECK (Len(Name)>1) UNIQUE
)

CREATE TABLE [Faculties]
(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL ,
[Name] NVARCHAR(100) NOT NULL CHECK (Len(Name)>1) UNIQUE ,
)

CREATE TABLE [Teachers]
(
[Id] INT IDENTITY(1,1) PRIMARY KEY NOT NULL ,
[EmploymentDate] DATE NOT NULL CHECK (EmploymentDate>'01.01.1990'),
[Name] NVARCHAR(MAX) NOT NULL CHECK(Len(Name)>1) ,
[Premium] MONEY NOT NULL CHECK (Premium>0) DEFAULT 0,
[Salary] MONEY NOT NULL CHECK (Salary>=0),
[Surname] NVARCHAR(MAX) NOT NULL CHECK (Len(Surname)>1)
)